### ISSUE TITLE
Put operation of an existing file overwrite existing file without a warning

### ISSUE THREAD

**Issue by ingridbr** [hpcleuven/vsc-python-irodsclient#1]
When doing a put of a file that already exist in iRODS the irods.bulk.put() function overwrite the file without any warning or information.

That seems to be also the  behaviour of the PRC session.data_objects.put() but it might be better to raise an error and suggest using the force option. 

I do not see otherwise what is the purpose of the force option if the default is to overwrite the file

**Comment by trel** [comment]
Agreed - a warning/requirement probably makes sense.    This is an interesting point of discussion.

The python-irodsclient uses open/write/close semantics, rather than object semantics of 'put' - so we have gone back and forth on whether to allow/require a force flag.   This use case is extremely important.

**Comment by MaximeVdB** [comment]
Thanks to you both for your input -- now, VSC-PRC's `bulk.put()` will not overwrite by default,
which can be overridden with `force=True` (regardless of how PRC behaves).

**Comment by ingridbr** [comment]
Excellent! Just out of curiosity before I can test it. How the warning will be handled? by file or bt transaction? 

For example, if a user put a a bunch of files (10) with the wildcard  *.dat and 1 or 2 of them already exist in the collection bit not the others. Wich kind of warning message will the user receive and what will be the behaviour of the put?

I see this possible scenario's:

- Show a message that some files already exist (without listing them) and cancel the whole transfer
- Show a message with the list of the existing files and cancel the whole transfer
- Show a message with the list of the existing files. Skip the put for those files,  do the put for the rest of the files and suggest using the force option for the other 

What is your approach?

**Comment by MaximeVdB** [comment]
I thought about it a bit more, and I figured that it would be best to stick
to the analogy with UNIX commands, meaning that:
* By default, existing files/data objects get overwritten (clobbered).
* By setting clobber=False, operations which would lead to clobbering
  are skipped, while other operations are performed as usual.

This mostly corresponds to your 3rd scenario.
