### ISSUE TITLE
Create a move bulk operation

### ISSUE THREAD

**Issue by ingridbr** [hpcleuven/vsc-python-irodsclient#3]
In the same line as the bulk operation for get and put that already exist it will be nice to also have a move bulk operation.
It should be based on the PRC functions:

 session.data_objects.move
 session.collections.move

but also adding wildcards and AVUs.

**Comment by MaximeVdB** [comment]
That's indeed one we need to have as well -- I've now added it to the set of bulk operations
and command line tools.

Selecting items based on e.g. glob patterns with wildcards and AVUs happens in the same ways
as the other operations.
